### ISSUE TITLE
xx

### ISSUE THREAD

**Issue by HelloF1sh** [cuhksz-nlp/SANER#14]
本人刚接触NLP，想请问作者使用Tencent Embedding 和ZEN Embedding出于什么样的考虑，为何不使用BERT，是出于模型运行速度的考虑还是说这两个词向量效果更佳呢？谢谢！

**Comment by nyy477** [comment]
hello，我们进行过许多的尝试，最后的结论是直接使用bert的效果没有目前的效果好。
使用tencent embedding和ZEN的原因是，这两个都是目前在中文领域都能够提供比较好的词向量
