### ISSUE TITLE
项目报错无法运行

### ISSUE THREAD

**Issue by SunYonge** [cuhksz-nlp/SANER#15]
return word2vec.WordVectors.from_text(fname, *args, **kwargs)
  File "/home/husy/anaconda3/envs/venv0_BERT-CMV/lib/python3.7/site-packages/word2vec/wordvectors.py", line 234, in from_text
    vocab_size, vector_size = list(map(int, header.split()))
**ValueError: invalid literal for int() with base 10: b'\xe7\x9a\x84'**

**Comment by thejacoblu** [comment]
同样的报错，参考了https://github.com/3Top/word2vec-api/issues/6，在tencent_unigram.txt的首行添加了vocab_size和vector_size的值，即22750 200

**Comment by SunYonge** [comment]
> 同样的报错，现在解决了吗

未解决，没有再看这篇文章的代码了，感觉这篇文章想法是不错的。

**Comment by thejacoblu** [comment]
> > 同样的报错，现在解决了吗
> 
> 未解决，没有再看这篇文章的代码了，感觉这篇文章想法是不错的。

好的谢谢 我继续看看 实在不行也不进行复现了

**Comment by nyy477** [comment]
hello，各位，为方便大家，我把预处理好之后的tencent_unigram.txt文件我放到网盘上了，大家自取，感谢对项目的关注~
链接: https://pan.baidu.com/s/1tS2ZCMdfTOGYwKwthcDGqw  密码: 0nob
