### ISSUE TITLE
some questions about data

### ISSUE THREAD

**Issue by tyistyler** [cuhksz-nlp/SANER#2]
Excuse me, I have some questions about data,
i put the tencent embedding in './data' and running
but does the tencent_unigram means extract the unigram from tencent?
THX!

**Comment by nyy477** [comment]
We have updated the preprocessing script for Tencent Embedding, and you can run `python data_process.py --file_path $PATH_TO_TENCENT_EMBEDDING$` to extract the unigrams from Tencent Embedding.

**Comment by tyistyler** [comment]
thanks， and could you update the preprocess about the chinese weibo data, because i use the data with '科 O\n 技 O\n.....' but return the error with expected sequecne of length * at dim 1 (got (*+1) or (*+2))
