### ISSUE TITLE
a error about sequecne of length x

### ISSUE THREAD

**Issue by tyistyler** [cuhksz-nlp/SANER#3]
thanks a lot， and could you update the preprocess about the chinese weibo data, because i use the data with '科 O\n 技 O\n.....' (from weiboNER_2nd_conll...) but return the error with "expected sequecne of length x at dim 1 (got (x+1) or (x+2))"

**Comment by tyistyler** [comment]
excuse me, the code maybe has some questions?
ex: when process the data: 
\# O 
微 O
博 O
桌 O
面 O
\# O
1 O
. O
3 O
......
i use the CNNERPipe.process_from_file (paths)  and get [‘微’,'博','桌','面'...]（seq's length = 157） which doesn't '#'，however， the feature_data'length about this sequence is 159, because the fearute_data has two '#'
How do you deal with it?
thanks!

**Comment by tyistyler** [comment]
the other is that when use the pretrained model, it return "  ModuleNotFoundError: No module named 'models.TENER'  " while our model isnot TENER

**Comment by nyy477** [comment]
Thanks and the problem has been solved.
