### ISSUE TITLE
tencent_unigram.txt 疑似有問題

### ISSUE THREAD

**Issue by fireindark707** [cuhksz-nlp/SANER#5]
已經準備好相關詞向量檔案。
運行python run_cn.py報錯：

Traceback (most recent call last):
  File "train_zen_cn.py", line 142, in <module>
    data_bundle, embed, bi_embed, train_feature_data, dev_feature_data, test_feature_data, feature2id, id2feature = load_data()
  File "SANER-master/fastNLP/core/utils.py", line 155, in wrapper
    results = func(*args, **kwargs)
  File "train_zen_cn.py", line 113, in load_data
    data_bundle.get_vocab('chars').word2idx, glove_path, dict_save_path
  File "SANER-master/get_context.py", line 10, in get_neighbor_for_vocab
    model = word2vec.load(dataPath)
  File "/usr/local/lib/python3.6/dist-packages/word2vec/io.py", line 18, in load
    return word2vec.WordVectors.from_text(fname, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/word2vec/wordvectors.py", line 255, in from_text
    vocab_size, vector_size = list(map(int, header.split()))
ValueError: invalid literal for int() with base 10: b'\xe7\x9a\x84'

此處dataPath對應tencent_unigram.txt，疑似是檔案問題

**Comment by alkaideemo** [comment]
> 
> 
> 已經準備好相關詞向量檔案。
> 運行python run_cn.py報錯：
> 
> Traceback (most recent call last):
> File "train_zen_cn.py", line 142, in
> data_bundle, embed, bi_embed, train_feature_data, dev_feature_data, test_feature_data, feature2id, id2feature = load_data()
> File "SANER-master/fastNLP/core/utils.py", line 155, in wrapper
> results = func(*args, **kwargs)
> File "train_zen_cn.py", line 113, in load_data
> data_bundle.get_vocab('chars').word2idx, glove_path, dict_save_path
> File "SANER-master/get_context.py", line 10, in get_neighbor_for_vocab
> model = word2vec.load(dataPath)
> File "/usr/local/lib/python3.6/dist-packages/word2vec/io.py", line 18, in load
> return word2vec.WordVectors.from_text(fname, *args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/word2vec/wordvectors.py", line 255, in from_text
> vocab_size, vector_size = list(map(int, header.split()))
> ValueError: invalid literal for int() with base 10: b'\xe7\x9a\x84'
> 
> 此處dataPath對應tencent_unigram.txt，疑似是檔案問題

word2vec library read word2vec format embedding. however tencent_unigram.txt is glove format, you need to add a line to the head of tencent_unigram.txt: 22750 200

**Comment by fireindark707** [comment]
> > 已經準備好相關詞向量檔案。
> > 運行python run_cn.py報錯：
> > Traceback (most recent call last):
> > File "train_zen_cn.py", line 142, in
> > data_bundle, embed, bi_embed, train_feature_data, dev_feature_data, test_feature_data, feature2id, id2feature = load_data()
> > File "SANER-master/fastNLP/core/utils.py", line 155, in wrapper
> > results = func(*args, **kwargs)
> > File "train_zen_cn.py", line 113, in load_data
> > data_bundle.get_vocab('chars').word2idx, glove_path, dict_save_path
> > File "SANER-master/get_context.py", line 10, in get_neighbor_for_vocab
> > model = word2vec.load(dataPath)
> > File "/usr/local/lib/python3.6/dist-packages/word2vec/io.py", line 18, in load
> > return word2vec.WordVectors.from_text(fname, *args, **kwargs)
> > File "/usr/local/lib/python3.6/dist-packages/word2vec/wordvectors.py", line 255, in from_text
> > vocab_size, vector_size = list(map(int, header.split()))
> > ValueError: invalid literal for int() with base 10: b'\xe7\x9a\x84'
> > 此處dataPath對應tencent_unigram.txt，疑似是檔案問題
> 
> word2vec library read word2vec format embedding. however tencent_unigram.txt is glove format, you need to add a line to the head of tencent_unigram.txt: 22750 200

really thanks for your response!
