### ISSUE TITLE
Wrong sequence length when process get_features

### ISSUE THREAD

**Issue by fireindark707** [cuhksz-nlp/SANER#6]
File "train_zen_cn.py", line 231, in <module>
    trainer.train(load_best_model=False)
  File "SANER-master/fastNLP/core/trainer.py", line 690, in train
    raise e
  File "SANER-master/fastNLP/core/trainer.py", line 683, in train
    self._train()
  File "SANER-master/fastNLP/core/trainer.py", line 775, in _train
    features = self.get_features(indices, seq_len=torch.max(batch_x.get("seq_len")).item())
  File "SANER-master/fastNLP/core/trainer.py", line 725, in get_features
    return torch.tensor(ret_list)
ValueError: expected sequence of length 49 at dim 1 (got 44)

I got many errors when process trainer. It seems that batch_x.get("seq_len") is different from real length.

Here is the print of data:

batch_x.get("seq_len"): tensor([43, 39, 41, 43, 37, 36, 37, 43, 31, 44, 33, 35, 25, 39, 41, 32, 37, 39,
        40, 40, 44, 38, 40, 39, 38, 35, 37, 38, 37, 36, 30, 35])
indices: [541, 369, 641, 990, 485, 709, 971, 545, 17, 112, 145, 198, 267, 412, 132, 1177, 609, 487, 95, 938, 161, 355, 481, 459, 781, 219, 949, 1105, 748, 1162, 855, 931]
seq_len:  44
temp_len:  49 for indices 541

**Comment by alkaideemo** [comment]
There's something wrong with the "get_features" function in trainer.py.  I adapted it to my own understanding.
```
if temp_len >= seq_len:
    ret_list.append(feature_data[:seq_len])
else:
    ret_list.append(feature_data + [[0] * self.context_num for _ in range(seq_len - temp_len)])
```

**Comment by nyy477** [comment]
Hi, thanks for the question. We have fix the bug and you can pull the code again.
