### ISSUE TITLE
W16的结果达不到论文结果，请问我是否需要修改哪些设置？

### ISSUE THREAD

**Issue by Ian-peace** [cuhksz-nlp/SANER#8]
并且，模型自动保存的模型大小只有11M，而您提供的模型大小有 2.26G，请问是什么原因？

W16上的训练结果如下，未更改代码的任何参数。
Best test performance(may not correspond to the best dev performance):{'SpanFPreRecMetric': {'f': 0.492514, 'pre': 0.537258, 'rec': 0.45465}} achieved at Epoch:47.                        
Best test performance(correspond to the best dev performance):{'SpanFPreRecMetric': {'f': 0.485886, 'pre': 0.54077, 'rec': 0.441117}} achieved at Epoch:46.

**Comment by nyy477** [comment]
你好，感谢对本工作的关注。
首先可能是数据集的问题，我们重新上传了数据集到`data/`文件夹；其次，如果保存模型只有11M，可能在embedding中没有用上ELMo和BERT，可以留意一下。
