### ISSUE TITLE
请问我如果想提取最后一层各token的embedding，应该怎么做？

### ISSUE THREAD

**Issue by Ian-peace** [cuhksz-nlp/SANER#9]
如题

**Comment by Ian-peace** [comment]
run_token_level_classification.py   无法直接运行，task_name 没办法匹配，您列出的那几个都不是对应W6这几个数据集的label形式

**Comment by nyy477** [comment]
run_token_level_classification.py的运行可以参考https://github.com/sinovation/ZEN
